version: "3.7"

services:
  db:
    image: quay.io/yingzhuo/regioncn-mysql:latest
    container_name: "regioncn-mysql"
    restart: "always"

  regioncn:
    image: quay.io/yingzhuo/regioncn:latest
    container_name: "regioncn"
    restart: "always"
    ports:
      - "18081:8080"
    links:
      - db:db
    command:
      - "docker-entrypoint"
      - "--response-type=protobuf"
      - "--mysql-host=db"
      - "--mysql-port=3306"
    environment:
      - "WAIT_FOR_READINESS=db:3306"
