# ----------------------------------------------------------------------------------------------------------------------
# Namespace
# ----------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: regioncn

# ----------------------------------------------------------------------------------------------------------------------
# Application
# ----------------------------------------------------------------------------------------------------------------------
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: regioncn
  namespace: regioncn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regioncn
      node: regioncn
  template:
    metadata:
      name: regioncn
      namespace: regioncn
      labels:
        app: regioncn
        node: regioncn
    spec:
      containers:
        - name: regioncn-mysql
          image: "quay.io/yingzhuo/regioncn-mysql:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
        - name: region
          image: "quay.io/yingzhuo/regioncn:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "WAIT_FOR_READINESS"
              value: "localhost:3306"
          command:
            - "docker-entrypoint"
            - "--mysql-host=localhost"
            - "--mysql-port=3306"

---

apiVersion: v1
kind: Service
metadata:
  name: regioncn
  namespace: regioncn
spec:
  selector:
    app: regioncn
    node: regioncn
  type: NodePort
  ports:
    - name: main
      port: 8080
      targetPort: 8080
      nodePort: 18081
